### ISSUE TITLE
not working sir

### ISSUE THREAD

**Issue by Kaatne-Wala-Kutta** [dhorseman1710/Decrypt-PluralSight-GUI#3] opened 2021-05-25 16:43 UTC
I guess it's not working now. I'm ready to help if you need any credentials. But after setting path, it shows 0 courses even course is there. I dunno where is the error.

**Comment by mrvogiacu** [comment] 2021-05-25 18:50
Did you select correct course and db folder patch?

**Comment by mahdisky** [comment] 2021-05-28 14:07
me too, i have this problem

**Comment by mrvogiacu** [comment] 2021-05-28 14:11
> me too, i have this problem

Please give me the screenshot when you already select the course path and db file path

**Comment by mahdisky** [comment] 2021-05-28 14:27
![2_LI](https://user-images.githubusercontent.com/34979288/119998758-41aa5f80-bfe6-11eb-94ef-bc3cb4f54696.jpg)
![2_LI (2)](https://user-images.githubusercontent.com/34979288/119998774-44a55000-bfe6-11eb-8cfa-b8e17f35cfe3.jpg)


![3](https://user-images.githubusercontent.com/34979288/119998949-774f4880-bfe6-11eb-84af-4b0d581bcb53.PNG)
this version is not complete subtitle convert to another folder

**Comment by mahdisky** [comment] 2021-05-28 14:34
yes in site have subtitle.
thns

**Comment by mrvogiacu** [comment] 2021-05-28 14:37
> yes in site have subtitle.
> thns

Can you give me the log file log folder?

**Comment by mrvogiacu** [comment] 2021-05-28 14:56
> where is it?
> 

 The log folder is the same directory with the execution file

**Comment by mahdisky** [comment] 2021-05-28 15:04
i cant found it , no file or folder as name log

**Comment by mahdisky** [comment] 2021-05-28 15:04
i cant found it , no file or folder as name log

**Comment by mrvogiacu** [comment] 2021-05-28 15:08
> i cant found it , no file or folder as name log

Ok. I will try to debug and reproduce it

**Comment by mrvogiacu** [comment] 2021-05-29 02:30
> i cant found it , no file or folder as name log

![image](https://user-images.githubusercontent.com/14990781/120055408-0482b380-c060-11eb-9036-c10ee6228441.png)

I can't reproduce this bug.
1. Did you have the logs folder (red block)?
2. If (1) isn't, please open the file in green block and check the content at the bottom of file, does it look like white block?
3. If (2) isn't, please correct it and send me the log file.
4. If yes, please zip the course folder (you can zip few course, not all) and DB file for me for debug?

**Comment by mahdisky** [comment] 2021-05-29 10:47
[2021-05-28.txt](https://github.com/dhorseman1710/Decrypt-PluralSight-GUI/files/6564512/2021-05-28.txt)
[2021-05-29.txt](https://github.com/dhorseman1710/Decrypt-PluralSight-GUI/files/6564513/2021-05-29.txt)
this is logs,


read course is slove,its ok, but subtitle not complete work :
![4](https://user-images.githubusercontent.com/34979288/120067466-fc8f3780-c090-11eb-9f41-301265a85cb0.PNG)

**Comment by mahdisky** [comment] 2021-05-29 10:52
sample video and db
[Uploading filesample.zip…]()
[pluralsight.zip](https://github.com/dhorseman1710/Decrypt-PluralSight-GUI/files/6564531/pluralsight.zip)

**Comment by mrvogiacu** [comment] 2021-05-29 11:26
> [2021-05-28.txt](https://github.com/dhorseman1710/Decrypt-PluralSight-GUI/files/6564512/2021-05-28.txt)
> [2021-05-29.txt](https://github.com/dhorseman1710/Decrypt-PluralSight-GUI/files/6564513/2021-05-29.txt)
> this is logs,
> 
> read course is slove,its ok, but subtitle not complete work :
> ![4](https://user-images.githubusercontent.com/34979288/120067466-fc8f3780-c090-11eb-9f41-301265a85cb0.PNG)

- base on the log, I think problem come from the logic to check clip is download complete or not. That why the tool get 0 courses.
- About the subtitle, i check the db file and with the clip `3. Common Architectural Setups` doesn't have subtitle

![image](https://user-images.githubusercontent.com/14990781/120068536-50a71580-c0ab-11eb-8c7f-46b2827e7309.png)

**Comment by mahdisky** [comment] 2021-05-29 11:35
yes, i remove this course and again  download it, thats true ,
thnks

**Comment by dhorseman1710** [comment] 2021-05-29 12:49
@Kaatne-Wala-Kutta @mahdisky 

This issue already fixed in the latest version - 1.9.2. Please download and try again

**Closed** 2021-06-15 11:35 UTC

**Comment by umarsolehri** [comment] 2022-06-24 14:23
I decrypt video using this tool but they got corrupted, is there any way to encrypt them back
![image](https://user-images.githubusercontent.com/15965524/175555567-ccc01315-6959-46fa-ae9e-0f782657d9a5.png)
